### ISSUE TITLE
notion_client.errors.RequestTimeoutError: Request to Notion API has timed out

### ISSUE THREAD

**Issue by ChituQAQ** [trustmaster/gkeep2notion#12]
Notion is not longer allowing API usage outside their apps?

output:
```
D:\Program** Files\Python\gkeep2notion-main>gkeep2notion.py
Loading access token from keyring
Authorization, this may take a while...
Logging into Notion
Traceback (most recent call last):
  File "D:\Program Files\Python39\lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "D:\Program Files\Python39\lib\site-packages\httpcore\backends\sync.py", line 62, in start_tls
    raise exc
  File "D:\Program Files\Python39\lib\site-packages\httpcore\backends\sync.py", line 57, in start_tls
    sock = ssl_context.wrap_socket(
  File "D:\Program Files\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\Program Files\Python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "D:\Program Files\Python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1112: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Python39\lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "D:\Program Files\Python39\lib\site-packages\httpx\_transports\default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "D:\Program Files\Python39\lib\site-packages\httpcore\_sync\connection_pool.py", line 253, in handle_request
    raise exc
  File "D:\Program Files\Python39\lib\site-packages\httpcore\_sync\connection_pool.py", line 237, in handle_request
    response = connection.handle_request(request)
  File "D:\Program Files\Python39\lib\site-packages\httpcore\_sync\http_proxy.py", line 261, in handle_request
    connect_response = self._connection.handle_request(
  File "D:\Program Files\Python39\lib\site-packages\httpcore\_sync\connection.py", line 86, in handle_request
    raise exc
  File "D:\Program Files\Python39\lib\site-packages\httpcore\_sync\connection.py", line 63, in handle_request
    stream = self._connect(request)
  File "D:\Program Files\Python39\lib\site-packages\httpcore\_sync\connection.py", line 150, in _connect
    stream = stream.start_tls(**kwargs)
  File "D:\Program Files\Python39\lib\site-packages\httpcore\backends\sync.py", line 62, in start_tls
    raise exc
  File "D:\Program Files\Python39\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\Program Files\Python39\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectTimeout: _ssl.c:1112: The handshake operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Program Files\Python39\lib\site-packages\notion_client\client.py", line 189, in request
    response = self.client.send(request)
  File "D:\Program Files\Python39\lib\site-packages\httpx\_client.py", line 908, in send
    response = self._send_handling_auth(
  File "D:\Program Files\Python39\lib\site-packages\httpx\_client.py", line 936, in _send_handling_auth
    response = self._send_handling_redirects(
  File "D:\Program Files\Python39\lib\site-packages\httpx\_client.py", line 973, in _send_handling_redirects
    response = self._send_single_request(request)
  File "D:\Program Files\Python39\lib\site-packages\httpx\_client.py", line 1009, in _send_single_request
    response = transport.handle_request(request)
  File "D:\Program Files\Python39\lib\site-packages\httpx\_transports\default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "D:\Program Files\Python39\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\Program Files\Python39\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout: _ssl.c:1112: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Python\gkeep2notion-main\gkeep2notion.py", line 372, in <module>
    create_page(notion, notes)
  File "D:\Program Files\Python\gkeep2notion-main\gkeep2notion.py", line 168, in create_page
    notion_page = notion.pages.create(parent=page.parent,
  File "D:\Program Files\Python39\lib\site-packages\notion_client\api_endpoints.py", line 197, in create
    return self.parent.request(
  File "D:\Program Files\Python39\lib\site-packages\notion_client\client.py", line 191, in request
    raise RequestTimeoutError()
notion_client.errors.RequestTimeoutError: Request to Notion API has timed out
```

**Comment by StrictLine** [comment]
My experience is, this comes up if I migrated lots of notes, so there might be an API throttling that gets hit after numerous requests to the Notion API.

**Comment by trustmaster** [comment]
As [Notion docs](https://developers.notion.com/reference/request-limits) say, Notion starts rate limiting beyond 3 requests per second. I have added throttling to this tool in the latest revision.
