### ISSUE TITLE
httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://api.notion.com/v1/pages'

### ISSUE THREAD

**Issue by edgewisegroup** [trustmaster/gkeep2notion#13]
:(

**Comment by pulyankote** [comment]
I get the same error as well :( 

> ./gkeep2notion.py
Loading access token from keyring
Authorization, this may take a while...
Logging into Notion
Traceback (most recent call last):
  File "xxxxx/notion_client/client.py", line 116, in _parse_response
    response.raise_for_status()
  File "xxxxxxx/httpx/_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://api.notion.com/v1/pages'
For more information check: https://httpstatuses.com/400

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "xxxxx/./gkeep2notion.py", line 372, in <module>
    create_page(notion, notes)
  File "xxxxx/./gkeep2notion.py", line 168, in create_page
    notion_page = notion.pages.create(parent=page.parent,
  File "xxxxx/notion_client/api_endpoints.py", line 197, in create
    return self.parent.request(
  File "xxxxx/notion_client/client.py", line 192, in request
    return self._parse_response(response)
  File "xxxxx/notion_client/client.py", line 124, in _parse_response
    raise APIResponseError(response, body["message"], code)
notion_client.errors.APIResponseError: body failed validation. Fix one:
body.parent.database_id should be defined, instead was `undefined`.
body.parent.page_id should be a valid uuid, instead was `""`.

**Comment by edgewisegroup** [comment]
The error message suggests that there was an issue with the request sent to Notion's API. A 400 Bad Request error usually indicates that the client (in this case, the script) has provided incorrect or malformed data in the request.

In the script, one possible reason for this error is that the root_url in the config file might be incorrect or improperly formatted. The root_url should be a valid Notion URL of the page where you want the imported Google Keep notes and todo lists to be placed.

To fix the issue, double-check the config.ini file and ensure that the root_url under the [notion] section is a valid Notion URL. If you have made changes to the config file, save it and re-run the script.

**Comment by Memorix101** [comment]
Yup. I got the same issue 😕

```
Logging into Notion
Traceback (most recent call last):
  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\notion_client\client.py", line 116, in _parse_response
    response.raise_for_status()
  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://api.notion.com/v1/pages'
For more information check: https://httpstatuses.com/400

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxxxxx\Downloads\gkeep2notion-main\gkeep2notion.py", line 372, in <module>
    create_page(notion, notes)
  File "C:\Users\xxxxxx\Downloads\gkeep2notion-main\gkeep2notion.py", line 168, in create_page
    notion_page = notion.pages.create(parent=page.parent,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\notion_client\api_endpoints.py", line 197, in create
    return self.parent.request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\notion_client\client.py", line 192, in request
    return self._parse_response(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\notion_client\client.py", line 124, in _parse_response
    raise APIResponseError(response, body["message"], code)
notion_client.errors.APIResponseError: body failed validation. Fix one:
body.parent.database_id should be defined, instead was `undefined`.
body.parent.page_id should be a valid uuid, instead was `""`.
```

**Comment by nemoitis** [comment]
I guess I found the issue. I don't know if this is a new system or not, I couldn't share the Page to my Integration, searching didn't show anything in share menu. After going through [notion documentation](https://www.notion.so/help/add-and-manage-connections-with-the-api#add-connections-to-pages),  I found you have to add connection (integration) to the page like this:

<img width="501" alt="image" src="https://user-images.githubusercontent.com/80112748/236410099-8d1c4ff3-c3ed-45c7-aa2a-ced9b9aa6f32.png">

Then copy the sharable link and put it in the `config.ini` file as instructed in readme. Make sure there are no quotations. This worked for me and I guess it will solve the issue here as well.
