### ISSUE TITLE
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'

### ISSUE THREAD

**Issue by WisnetSaga** [trustmaster/gkeep2notion#18]
i did manage to get passed the part where i give it my password & it saves it, when i run the script again however, it doesnt seem to be running properly

```python
Traceback (most recent call last):
  File "/Users/wisnet/Downloads/GKN/gkeep2notion-main/./gkeep2notion.py", line 11, in <module>
    from gkeepapi import Keep, node
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/gkeepapi/__init__.py", line 15, in <module>
    import gpsoauth
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/gpsoauth/__init__.py", line 9, in <module>
    import requests
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/urllib3/__init__.py", line 7, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import IncompleteRead as httplib_IncompleteRead
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'
``` 

im on mac OS btw.

**Comment by trustmaster** [comment]
There is a workaround for this issue now with Docker. Check the updated Readme.
